name: sp
favicon: null
layout_spectrum: 0.9688355466350913
typography_spectrum: 0.3787632614839822
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.23580490937456489
  lightness: 0.7706045021768659
  saturation: 0.22793864528648555
  rhythmicContrast: 0.2855761481914669
purpose: []
