layout_spectrum: 0.9688355466350913
favicon: null
name: sp
purpose: []
analytics:
  twitter: null
  google: null
  facebook: null
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  version: null
  bucket: null
  domain: null
color:
  brandStrength: 0.5106383
  lightness: 0.7893617
  saturation: 0.4340425
  rhythmicContrast: 0.5234042
  brandColors:
    - '#F2EFEC'
    - '#0E1D27'
    - '#02416E'
    - '#D8A488'
    - '#A3654B'
typography_spectrum: 0.5021276
